[package]
name = "orchard"
version = "0.0.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
]
edition = "2018"
description = "Sapling on stilts!"
license-file = "LICENSE-BOSL"
repository = "https://github.com/zcash/orchard"
documentation = "https://docs.rs/orchard"
readme = "README.md"

# We are not publishing this yet.
publish = false

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
aes = "0.6"
arrayvec = "0.7.0"
bitvec = "0.22"
blake2b_simd = "0.5"
ff = "0.10"
fpe = "0.4"
group = "0.10"
lazy_static = "1"
pasta_curves = "0.1"
proptest = { version = "1.0.0", optional = true }
rand = "0.8"
nonempty = "0.6"
subtle = "2.3"

# Developer tooling dependencies
plotters = { version = "0.3.0", optional = true }

[dependencies.halo2]
git = "https://github.com/zcash/halo2.git"
rev = "d8e4f24df44da94ab5cacbc531517e2b63fe45ee"

[dependencies.reddsa]
git = "https://github.com/str4d/redjubjub.git"
rev = "d5d8c5f3bb704bad8ae88fe4a29ae1f744774cb2"

[dev-dependencies]
criterion = "0.3"
hex = "0.4"
proptest = "1.0.0"

[lib]
bench = false

[features]
dev-graph = ["halo2/dev-graph", "plotters"]
test-dependencies = ["proptest"]

[[bench]]
name = "small"
harness = false
