name: Nightly lints

# These lints are only informative, so we only run them directly on branches
# and not trial-merges of PRs, to reduce noise.
on: push

jobs:
  clippy-nightly:
    name: Clippy (nightly)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run Clippy (nightly)
        uses: actions-rs/clippy-check@v1
        continue-on-error: true
        with:
          name: Clippy (nightly)
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets

